name: ndk-pkg-brew-version-compare

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  schedule:

    runs-on: macos-12

    steps:
      - run: brew update

      - uses: actions/checkout@v3

      - run: ./ndk-pkg env
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg update

      - run: |
          cd ~/.ndk-pkg/repos.d/offical-core
          git fetch --progress origin +refs/heads/dev:refs/remotes/origin/dev
          git checkout dev
        if: ${{ github.ref_name == 'dev' }}

      - run: ./ndk-pkg compare-versions brew
      - run: ./ndk-pkg compare-versions maven
