name: publish ndk-pkg core

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: input a release version to be published
        required: true

jobs:

  macos:
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        target-version: ['10.15', '11.0', '12.0', '13.0', '14.0']
        target-arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4

      - run: install -d out/

      - run: mv fonts.conf out/

      - run: |
          for item in *.c
          do
            clang -std=c99 -Os -flto -Wl,-s -o "out/${item%.c}" "$item"
          done

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup
      - run: ./xcpkg update
      - run: ./xcpkg install MacOSX-${{ matrix.target-version }}-${{ matrix.target-arch }}/uppm@0.15.1 --link-type=static-most
      - run: ./xcpkg pack    MacOSX-${{ matrix.target-version }}-${{ matrix.target-arch }}/uppm@0.15.1 -o .

      - run: tar vxf uppm*.tar.xz -C out --strip-components=1
      - run: mv out/bin/uppm out/
      - run: rm -rf out/bin
      - run: rm -rf out/shared
      - run: rm -rf out/.xcpkg

      - run: |
          DIRNAME="ndk-pkg-core-${{ inputs.release-version }}-macos-${{ matrix.target-version }}-${{ matrix.target-arch }}"
          mv out "$DIRNAME"
          tar cJvf "$DIRNAME.tar.xz" "$DIRNAME"

      - uses: actions/upload-artifact@v4
        with:
          name: ndk-pkg-core-macos-${{ matrix.target-version }}-${{ matrix.target-arch }}.tar.xz
          path: ndk-pkg-core-*.tar.xz


  linux:
    runs-on: ubuntu-latest

    container: alpine:3.19

    steps:
      - run: apk update
      - run: apk add curl xz g++ libc-dev linux-headers

      - uses: actions/checkout@v4

      - run: install -d out/

      - run: mv fonts.conf out/

      - run: |
          for item in *.c
          do
            gcc -std=c99 -Os -flto -Wl,-s -static -o "out/${item%.c}" "$item"
          done

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install uppm@0.15.1 --link-type=static-full
      - run: ./ppkg pack    uppm@0.15.1 -o .

      - run: tar vxf uppm*.tar.xz -C out --strip-components=1
      - run: mv out/bin/uppm out/
      - run: rm -rf out/bin
      - run: rm -rf out/shared
      - run: rm -rf out/.ppkg

      - run: |
          DIRNAME="ndk-pkg-core-${{ inputs.release-version }}-linux-x86_64"
          mv out "$DIRNAME"
          tar cJvf "$DIRNAME.tar.xz" "$DIRNAME"

      - uses: actions/upload-artifact@v4
        with:
          name: ndk-pkg-core-linux-x86_64.tar.xz
          path: ndk-pkg-core-*.tar.xz


  publish:

    needs: [macos, linux]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      - run: |
          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          SHA256SUM="$(sha256sum ndk-pkg-core-*.tar.xz)"

          cat > notes.md <<EOF
          sha256sum:

          \`\`\`
          $SHA256SUM
          \`\`\`
          EOF

          gh release create ndk-pkg-core-${{ inputs.release-version }} ndk-pkg-core-*.tar.xz --title ndk-pkg-core-${{ inputs.release-version }} --notes-file notes.md
